# Generated by Django 5.2.6 on 2025-10-16 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sgexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('exam_date', models.DateField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/', verbose_name='Задание (изображение)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('participants', models.ManyToManyField(related_name='sgexam_participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
    ]
